name: Deploy built directory to S3

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Configure Yarn
        uses: DerYeger/yarn-setup-action@v1.0.1
        with:
          node-version: 16.20.2
      - run: yarn && yarn build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-southeast-1' # Change this to your desired AWS region

      - name: Upload to S3
        run: aws s3 sync ./dist s3://www.zicotjia.com/
